# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\TE\QTdesignedfile\test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplcanvaswrapper import MplCanvasWrapper


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 700)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = MplCanvasWrapper(parent=self.centralwidget,title='yali',valueName='N')
        self.widget.setGeometry(QtCore.QRect(90, 80, 500, 300))
        self.widget.setObjectName("widget")
        self.widget_2 = MplCanvasWrapper(parent=self.centralwidget,title='weiyi',valueName='cm')
        self.widget_2.setGeometry(QtCore.QRect(580, 80,500, 300))
        self.widget_2.setObjectName("widget_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 20, 561, 41))
        self.textEdit.setObjectName("textEdit")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(380, 510, 321, 101))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("C:/Users/10938/Desktop/image.jpg"))
        self.Image.setObjectName("Image")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Begin = QtWidgets.QPushButton(self.centralwidget)
        self.Begin.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        self.Begin.setFont(font)
        self.Begin.setObjectName("Begin")
        self.Pause = QtWidgets.QPushButton(self.centralwidget)
        self.Pause.setGeometry(QtCore.QRect(100, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(16)
        self.Pause.setFont(font)
        self.Pause.setObjectName("Pause")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(250, 360, 761, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(250, 420, 761, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        self.error.setFont(font)
        self.error.setObjectName("error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">Intelligent parameter detection system</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "State analysis:"))
        self.label_3.setText(_translate("MainWindow", "Error message:"))
        self.Begin.setText(_translate("MainWindow", "Begin"))
        self.Pause.setText(_translate("MainWindow", "Pause"))
        self.state.setText(_translate("MainWindow", "Everything is OK"))
        self.error.setText(_translate("MainWindow", "Everything is OK"))

